export const SCREEN_ROUTER_APP = {
  HOME: 'HOME',
  EXPERIENCES: 'EXPERIENCES',
  EXPERIENCESDETAIL: 'EXPERIENCES',
  EXPERIENCESINTINERARY: 'EXPERIENCESINTINERARY',
  EXPERIENCESREVIEW: 'EXPERIENCESREVIEW',
  EXPERIENCESSEARCH: 'EXPERIENCESSEARCH',
  EXPERIENCESRESULT: 'EXPERIENCESRESULT',
  EXPERIENCESBOOKING: 'EXPERIENCESBOOKING',
};
